export default [{
    id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
    shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
    longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
    state: "Lagos",
    reporterName: "Remilekun Olowoigbo",
    email: "remilekun.olowoigbo@example.com",
    phone: 9011223344,
    updatedAt: "2020-01-28T19:55:58.591Z",
    createdAt: "2020-01-28T19:55:58.591Z",
    status: "open"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "in court"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "in court"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "open"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "open"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "in court"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "in court"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "open"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "open"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "in court"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "in court"
}, {
  id: "0c047b41-3e5b-41dc-b35d-2c6491468db4",
  shortDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing.",
  longDescription: "Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui. Ea ad aliquip ex magna sint aliquip esse laborum esse aliqua aute do officia ut labore non labore pariatur cupidatat adipisicing exercitation fugiat id est laboris ad velit incididunt qui",
  state: "Lagos",
  reporterName: "Remilekun Olowoigbo",
  email: "remilekun.olowoigbo@example.com",
  phone: 9011223344,
  updatedAt: "2020-01-28T19:55:58.591Z",
  createdAt: "2020-01-28T19:55:58.591Z",
  status: "open"
}];